wordpress:
        image: wordpress
        links:
                - wordpress_db:mysql
        ports:
                - "8080:80"
        
wordpress_db:
        image: mariadb
        environment:
                MYSQL_ROOT_PASSWORD: test
        
phpmyadmin:                
        image: phpmyadmin/phpmyadmin
        environment:
                MYSQL_ROOT_PASSWORD: test
        links:
                - wordpress_db:mysql
        ports:
                - "8181:80"

